spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enable: true
      path: /h2
#    datasource:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:~/test;NON_KEYWORDS=User
#      username: sa
#      password:

